# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-09-19 02:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aihao',
            fields=[
                ('idname', models.IntegerField(primary_key=True, serialize=False)),
                ('tiyu', models.CharField(blank=True, max_length=255, null=True)),
                ('food', models.CharField(blank=True, max_length=255, null=True)),
                ('book', models.CharField(blank=True, max_length=255, null=True)),
                ('movies', models.CharField(blank=True, max_length=255, null=True)),
                ('jiemu', models.CharField(blank=True, max_length=255, null=True)),
                ('xiuxian', models.CharField(blank=True, max_length=255, null=True)),
                ('aihao', models.CharField(blank=True, max_length=255, null=True)),
                ('trip', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Basics',
            fields=[
                ('idname', models.IntegerField(primary_key=True, serialize=False)),
                ('chird', models.CharField(blank=True, max_length=255, null=True)),
                ('area', models.CharField(blank=True, max_length=255, null=True)),
                ('xuexing', models.CharField(blank=True, max_length=255, null=True)),
                ('ethnic', models.CharField(blank=True, max_length=255, null=True)),
                ('salary', models.CharField(blank=True, max_length=255, null=True)),
                ('house', models.CharField(blank=True, max_length=255, null=True)),
                ('car', models.CharField(blank=True, max_length=255, null=True)),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
                ('lifename', models.CharField(blank=True, max_length=255, null=True)),
                ('shenfen', models.CharField(blank=True, max_length=255, null=True)),
                ('qq', models.CharField(blank=True, max_length=255, null=True)),
                ('adrr', models.CharField(blank=True, max_length=255, null=True)),
                ('youbian', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bodyshape',
            fields=[
                ('idname', models.IntegerField(primary_key=True, serialize=False)),
                ('weight', models.CharField(blank=True, max_length=255, null=True)),
                ('bodyshape', models.CharField(blank=True, max_length=255, null=True)),
                ('face', models.CharField(blank=True, max_length=255, null=True)),
                ('eyes', models.CharField(blank=True, max_length=255, null=True)),
                ('hair', models.CharField(blank=True, max_length=255, null=True)),
                ('skin', models.CharField(blank=True, max_length=255, null=True)),
                ('color', models.CharField(blank=True, max_length=255, null=True)),
                ('muscle', models.CharField(blank=True, max_length=255, null=True)),
                ('health', models.CharField(blank=True, max_length=255, null=True)),
                ('dress', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dubai',
            fields=[
                ('idname', models.IntegerField(primary_key=True, serialize=False)),
                ('dubai', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Econ',
            fields=[
                ('idname', models.IntegerField(primary_key=True, serialize=False)),
                ('licai', models.CharField(blank=True, max_length=255, null=True)),
                ('wazhai', models.CharField(blank=True, max_length=255, null=True)),
                ('jingjiguang', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hunyin',
            fields=[
                ('idname', models.IntegerField(primary_key=True, serialize=False)),
                ('jiguan', models.CharField(blank=True, max_length=255, null=True)),
                ('guoji', models.CharField(blank=True, max_length=255, null=True)),
                ('gexing', models.CharField(blank=True, max_length=255, null=True)),
                ('youmo', models.CharField(blank=True, max_length=255, null=True)),
                ('piqi', models.CharField(blank=True, max_length=255, null=True)),
                ('taidu', models.CharField(blank=True, max_length=255, null=True)),
                ('chird', models.CharField(blank=True, max_length=255, null=True)),
                ('jiehun', models.CharField(blank=True, max_length=255, null=True)),
                ('yidilian', models.CharField(blank=True, max_length=255, null=True)),
                ('nicehunyin', models.CharField(blank=True, max_length=255, null=True)),
                ('tongzhu', models.CharField(blank=True, max_length=255, null=True)),
                ('paihang', models.CharField(blank=True, max_length=255, null=True)),
                ('jiemei', models.CharField(blank=True, max_length=255, null=True)),
                ('fumu', models.CharField(blank=True, max_length=255, null=True)),
                ('fuwork', models.CharField(blank=True, max_length=255, null=True)),
                ('muwork', models.CharField(blank=True, max_length=255, null=True)),
                ('fumuqian', models.CharField(blank=True, max_length=255, null=True)),
                ('fmyibao', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lifestyle',
            fields=[
                ('idname', models.IntegerField(primary_key=True, serialize=False)),
                ('smoke', models.CharField(blank=True, max_length=255, null=True)),
                ('drink', models.CharField(blank=True, max_length=255, null=True)),
                ('exercise', models.CharField(blank=True, max_length=255, null=True)),
                ('eat', models.CharField(blank=True, max_length=255, null=True)),
                ('shopping', models.CharField(blank=True, max_length=255, null=True)),
                ('religious', models.CharField(blank=True, max_length=255, null=True)),
                ('testtime', models.CharField(blank=True, max_length=255, null=True)),
                ('network', models.CharField(blank=True, max_length=255, null=True)),
                ('maxspend', models.CharField(blank=True, max_length=255, null=True)),
                ('jiawu', models.CharField(blank=True, max_length=255, null=True)),
                ('housework', models.CharField(blank=True, max_length=255, null=True)),
                ('pet', models.CharField(blank=True, max_length=255, null=True)),
                ('aboutpet', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Workandstudy',
            fields=[
                ('idname', models.IntegerField(primary_key=True, serialize=False)),
                ('danwei', models.CharField(blank=True, max_length=255, null=True)),
                ('hangye', models.CharField(blank=True, max_length=255, null=True)),
                ('jobtype', models.CharField(blank=True, max_length=255, null=True)),
                ('daiyu', models.CharField(blank=True, max_length=255, null=True)),
                ('workingstate', models.CharField(blank=True, max_length=255, null=True)),
                ('diaodong', models.CharField(blank=True, max_length=255, null=True)),
                ('haiwai', models.CharField(blank=True, max_length=255, null=True)),
                ('careerfamily', models.CharField(blank=True, max_length=255, null=True)),
                ('gratitudefrom', models.CharField(blank=True, max_length=255, null=True)),
                ('major', models.CharField(blank=True, max_length=255, null=True)),
                ('language', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Xingfu',
            fields=[
                ('idname', models.IntegerField(primary_key=True, serialize=False)),
                ('nam', models.CharField(blank=True, max_length=255, null=True)),
                ('picture', models.CharField(blank=True, max_length=255, null=True)),
                ('time', models.CharField(blank=True, max_length=255, null=True)),
                ('area', models.CharField(blank=True, max_length=255, null=True)),
                ('condition', models.CharField(blank=True, max_length=255, null=True)),
                ('age', models.CharField(blank=True, max_length=255, null=True)),
                ('liuyan', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Zhaopian',
            fields=[
                ('idname', models.IntegerField(primary_key=True, serialize=False)),
                ('pic', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Zhuce',
            fields=[
                ('idname', models.IntegerField(primary_key=True, serialize=False)),
                ('sex', models.CharField(blank=True, max_length=255, null=True)),
                ('birthday', models.CharField(blank=True, max_length=255, null=True)),
                ('area', models.CharField(blank=True, max_length=255, null=True)),
                ('hunyin', models.CharField(blank=True, max_length=255, null=True)),
                ('tall', models.CharField(blank=True, max_length=255, null=True)),
                ('xueli', models.CharField(blank=True, max_length=255, null=True)),
                ('salary', models.CharField(blank=True, max_length=255, null=True)),
                ('password', models.IntegerField()),
                ('nam', models.CharField(blank=True, max_length=255, null=True)),
                ('jieshao', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
